version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:80
    environment:
      - APP_NAME=Laravel
      - APP_ENV=local
      - APP_KEY=base64:uhhk0d65kCfBXLLG2jwX23en+EtF3VbRitsSyIsulOc=
      - APP_DEBUG=true
      - APP_URL=http://localhost:80
      - FILESYSTEM_DISK=local
      - LOG_DEPRECATIONS_CHANNEL=null
      - LOG_LEVEL=debug
      - DB_CONNECTION=pgsql
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_DATABASE=app
      - DB_USERNAME=user
      - DB_PASSWORD=pass
      - AMQP_HOST=rabbitmq
      - AMQP_PORT=5672
      - AMQP_USER=guest
      - AMQP_PASSWORD=guest
      - QUEUE_CONNECTION=sync
      - L5_SWAGGER_GENERATE_ALWAYS=true
