version: "3.8"

services:
  app:
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
    volumes:
      - ./dev-db-init.sql:/docker-entrypoint-initdb.d/init.sql