version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.development
    entrypoint: sleep infinity
    ports:
      - "8002:80"
    volumes:
      - ./application:/app